apiVersion: v1
kind: ConfigMap
metadata:
  name: sre-agent-env
  namespace: sre
data:
  LLM_PROVIDER: "groq"
  MCP_K8S_URI: "http://mcp-k8s-real.sre.svc.cluster.local:3000"
  MCP_LOGS_URI: "http://mcp-loki-real.sre.svc.cluster.local:3000"
  MCP_METRICS_URI: "http://mcp-prometheus-real.sre.svc.cluster.local:3000"
  MCP_RUNBOOKS_URI: "http://mcp-notion-real.sre.svc.cluster.local:3000"
  MCP_GITHUB_URI: "http://mcp-github-real.sre.svc.cluster.local:3000"
  MCP_MEMORY_URI: "http://mcp-memory-real.sre.svc.cluster.local:3000"
